
    create table tb_category (
        active boolean not null,
        created_at TIMESTAMP WITHOUT TIME ZONE,
        id bigint generated by default as identity,
        updated_at TIMESTAMP WITHOUT TIME ZONE,
        name varchar(80) not null unique,
        description varchar(255),
        primary key (id)
    );

    create table tb_email (
        created_at TIMESTAMP WITHOUT TIME ZONE not null,
        id bigint generated by default as identity,
        content TEXT not null,
        recipient varchar(255) not null,
        sender varchar(255) not null,
        status enum ('ERROR','PENDING','SENT') not null,
        primary key (id)
    );

    create table tb_product (
        active boolean not null,
        price float(53),
        created_at TIMESTAMP WITHOUT TIME ZONE,
        id bigint generated by default as identity,
        updated_at TIMESTAMP WITHOUT TIME ZONE,
        description TEXT,
        img_url varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table tb_product_category (
        category_id bigint not null,
        product_id bigint not null,
        primary key (category_id, product_id)
    );

    create table tb_role (
        id bigint generated by default as identity,
        authority varchar(255),
        primary key (id)
    );

    create table tb_token (
        disabled boolean not null,
        created_at TIMESTAMP WITHOUT TIME ZONE not null,
        expire_date TIMESTAMP WITHOUT TIME ZONE not null,
        id bigint generated by default as identity,
        user_id bigint not null,
        token varchar(255) not null unique,
        type enum ('ACTIVATION','PASSWORD_RECOVERY') not null,
        primary key (id)
    );

    create table tb_user (
        active boolean not null,
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        first_name varchar(255),
        last_name varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table tb_user_role (
        role_id bigint not null,
        user_id bigint not null,
        primary key (role_id, user_id)
    );

    alter table if exists tb_product_category 
       add constraint FK5r4sbavb4nkd9xpl0f095qs2a 
       foreign key (category_id) 
       references tb_category;

    alter table if exists tb_product_category 
       add constraint FKgbof0jclmaf8wn2alsoexxq3u 
       foreign key (product_id) 
       references tb_product;

    alter table if exists tb_token 
       add constraint FKgvxl8jsfjnhlyu6oufm0rb5hx 
       foreign key (user_id) 
       references tb_user;

    alter table if exists tb_user_role 
       add constraint FKea2ootw6b6bb0xt3ptl28bymv 
       foreign key (role_id) 
       references tb_role;

    alter table if exists tb_user_role 
       add constraint FK7vn3h53d0tqdimm8cp45gc0kl 
       foreign key (user_id) 
       references tb_user;
