package com.albertsilva.dev.dscatalog.repository;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Optional;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;

import com.albertsilva.dev.dscatalog.entity.Category;
import com.albertsilva.dev.dscatalog.entity.Product;
import com.albertsilva.dev.dscatalog.factory.CategoryFactory;
import com.albertsilva.dev.dscatalog.factory.ProductFactory;

@DataJpaTest
@DisplayName("CategoryRepository Tests")
class CategoryRepositoryTest {

  @Autowired
  private CategoryRepository categoryRepository;

  @Autowired
  private ProductRepository productRepository;

  @Nested
  @DisplayName("Save Operations")
  class SaveOperations {

    @Test
    @DisplayName("should persist category with auto-generated id when id is null")
    void shouldPersistCategoryWithAutoGeneratedIdWhenIdIsNull() {

      // Arrange
      long countBefore = categoryRepository.count();

      Category category = CategoryFactory.createCategory();
      category.setId(null);

      // Act
      Category savedCategory = categoryRepository.save(category);

      // Assert
      assertThat(savedCategory.getId())
          .as("Category id should be auto-generated")
          .isNotNull()
          .isPositive();

      assertThat(categoryRepository.count()).as("Repository count should increase by one").isEqualTo(countBefore + 1);
    }

    @Test
    @DisplayName("should update category when id exists")
    void shouldUpdateCategoryWhenIdExists() {

      // Arrange
      Category category = categoryRepository.save(CategoryFactory.createCategory());
      String updatedName = "Updated Category";

      // Act
      category.setName(updatedName);
      Category updatedCategory = categoryRepository.save(category);

      // Assert
      assertThat(updatedCategory.getName()).as("Category name should be updated").isEqualTo(updatedName);
    }
  }

  @Nested
  @DisplayName("FindById Operations")
  class FindByIdOperations {

    @Test
    @DisplayName("should return category when id exists")
    void shouldReturnCategoryWhenIdExists() {

      // Arrange
      Category category = categoryRepository.saveAndFlush(CategoryFactory.createCategory());

      // Act
      Optional<Category> result = categoryRepository.findById(category.getId());

      // Assert
      assertThat(result).as("Category should be found").isPresent().contains(category);
    }

    @Test
    @DisplayName("should return empty optional when id does not exist")
    void shouldReturnEmptyOptionalWhenIdDoesNotExist() {

      // Arrange
      Long nonExistingId = 999999L;

      // Act
      Optional<Category> result = categoryRepository.findById(nonExistingId);

      // Assert
      assertThat(result).as("Category should not be found").isEmpty();
    }
  }

  @Nested
  @DisplayName("Search Operations")
  class SearchOperations {

    @Test
    @DisplayName("should return categories containing name ignoring case")
    void shouldReturnCategoriesContainingNameIgnoringCase() {

      // Arrange
      Category electronics = CategoryFactory.createCategory("Electronics-Test");

      Category books = CategoryFactory.createCategory("Books-Test");

      categoryRepository.saveAndFlush(electronics);
      categoryRepository.saveAndFlush(books);

      Pageable pageable = PageRequest.of(0, 10);

      // Act
      Page<Category> result = categoryRepository.findByNameContainingIgnoreCase("elec", pageable);

      // Assert
      List<String> names = result.getContent().stream().map(Category::getName).toList();

      assertThat(names)
          .as("Should return categories containing 'elec' ignoring case")
          .contains("Electronics-Test")
          .doesNotContain("Books-Test");
    }

    @Test
    @DisplayName("should return empty page when no category matches")
    void shouldReturnEmptyPageWhenNoCategoryMatches() {

      // Arrange
      categoryRepository.saveAndFlush(CategoryFactory.createCategory());

      Pageable pageable = PageRequest.of(0, 10);

      // Act
      Page<Category> result = categoryRepository.findByNameContainingIgnoreCase("NonExistingCategory", pageable);

      // Assert
      assertThat(result.getContent()).as("Should return empty result").isEmpty();
    }

    @Test
    @DisplayName("should return categories ordered alphabetically when sorted by name")
    void shouldReturnCategoriesOrderedAlphabeticallyWhenSortedByName() {

      // Arrange
      Category c1 = CategoryFactory.createCategory("Zebra-Test");
      Category c2 = CategoryFactory.createCategory("Apple-Test");
      Category c3 = CategoryFactory.createCategory("Books-Test");

      categoryRepository.saveAndFlush(c1);
      categoryRepository.saveAndFlush(c2);
      categoryRepository.saveAndFlush(c3);

      Pageable pageable = PageRequest.of(0, 10, org.springframework.data.domain.Sort.by("name"));

      // Act
      Page<Category> result = categoryRepository.findAll(pageable);

      // Assert
      var names = result.getContent().stream().map(Category::getName).toList();

      var sortedNames = new ArrayList<>(names);
      Collections.sort(sortedNames);

      assertThat(names).as("Categories should be sorted alphabetically").isEqualTo(sortedNames);
    }
  }

  @Nested
  @DisplayName("Delete Operations")
  class DeleteOperations {

    @Test
    @DisplayName("should delete category when id exists")
    void shouldDeleteCategoryWhenIdExists() {

      // Arrange
      Category category = categoryRepository.saveAndFlush(CategoryFactory.createCategory());
      Long existingId = category.getId();

      // Act
      categoryRepository.deleteById(existingId);
      categoryRepository.flush();

      // Assert
      assertThat(categoryRepository.existsById(existingId)).as("Category should be deleted").isFalse();
    }

    @Test
    @DisplayName("should decrease repository count after delete")
    void shouldDecreaseRepositoryCountAfterDelete() {

      // Arrange
      Category category = categoryRepository.saveAndFlush(CategoryFactory.createCategory());
      long countBefore = categoryRepository.count();

      // Act
      categoryRepository.deleteById(category.getId());
      categoryRepository.flush();

      // Assert
      assertThat(categoryRepository.count()).as("Repository count should decrease by one").isEqualTo(countBefore - 1);
    }

    @Test
    @DisplayName("should delete category without deleting associated products")
    void shouldDeleteCategoryWithoutDeletingAssociatedProducts() {

      // Arrange
      Category category = categoryRepository.saveAndFlush(CategoryFactory.createCategory());

      Product product = ProductFactory.createProduct();
      product.getCategories().add(category);
      product = productRepository.saveAndFlush(product);

      Long categoryId = category.getId();
      Long productId = product.getId();

      product.getCategories().remove(category);
      productRepository.saveAndFlush(product);

      // Act
      categoryRepository.deleteById(categoryId);
      categoryRepository.flush();

      // Assert
      assertThat(categoryRepository.existsById(categoryId)).as("Category should be deleted").isFalse();

      assertThat(productRepository.existsById(productId)).as("Associated product should remain").isTrue();
    }
  }
}