package com.albertsilva.dev.dscatalog.repository;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.List;
import java.util.Optional;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;

import com.albertsilva.dev.dscatalog.domain.recovery.Email;
import com.albertsilva.dev.dscatalog.domain.recovery.enums.EmailStatus;
import com.albertsilva.dev.dscatalog.dto.email.request.EmailRegisterRequest;

@DataJpaTest
@DisplayName("EmailRepository Tests")
class EmailRepositoryTest {

  @Autowired
  private EmailRepository emailRepository;

  @Nested
  @DisplayName("Save Operations")
  class SaveOperations {

    @Test
    @DisplayName("should persist email with auto-generated id and pending status")
    void shouldPersistEmailWithAutoGeneratedIdAndPendingStatus() {
      // Arrange
      long countBefore = emailRepository.count();
      Email email = createEmail();

      // Act
      Email savedEmail = emailRepository.saveAndFlush(email);

      // Assert
      assertThat(savedEmail.getId()).isNotNull().isPositive();
      assertThat(savedEmail.getStatus()).isEqualTo(EmailStatus.PENDING);
      assertThat(savedEmail.getCreatedAt()).isNotNull();
      assertThat(emailRepository.count()).isEqualTo(countBefore + 1);
    }

    @Test
    @DisplayName("should update email fields when id exists")
    void shouldUpdateEmailFieldsWhenIdExists() {
      // Arrange
      Email email = emailRepository.saveAndFlush(createEmail());
      email.setStatus(EmailStatus.SENT);
      email.setContent("Updated content");

      // Act
      Email updatedEmail = emailRepository.saveAndFlush(email);

      // Assert
      assertThat(updatedEmail.getStatus()).isEqualTo(EmailStatus.SENT);
      assertThat(updatedEmail.getContent()).isEqualTo("Updated content");
    }
  }

  @Nested
  @DisplayName("FindById Operations")
  class FindByIdOperations {

    @Test
    @DisplayName("should return email when id exists")
    void shouldReturnEmailWhenIdExists() {
      // Arrange
      Email savedEmail = emailRepository.saveAndFlush(createEmail());

      // Act
      Optional<Email> result = emailRepository.findById(savedEmail.getId());

      // Assert
      assertThat(result).isPresent();
      assertThat(result.get().getRecipient()).isEqualTo("recipient@example.com");
      assertThat(result.get().getSender()).isEqualTo("sender@example.com");
    }

    @Test
    @DisplayName("should return empty when id does not exist")
    void shouldReturnEmptyWhenIdDoesNotExist() {
      // Act
      Optional<Email> result = emailRepository.findById(999999L);

      // Assert
      assertThat(result).isEmpty();
    }
  }

  @Nested
  @DisplayName("FindAll Operations")
  class FindAllOperations {

    @Test
    @DisplayName("should return all persisted emails")
    void shouldReturnAllPersistedEmails() {
      // Arrange
      emailRepository.saveAndFlush(createEmail("first@example.com", "First content"));
      emailRepository.saveAndFlush(createEmail("second@example.com", "Second content"));

      // Act
      List<Email> result = emailRepository.findAll();

      // Assert
      assertThat(result).extracting(Email::getRecipient)
          .contains("first@example.com", "second@example.com");
    }

    @Test
    @DisplayName("should return empty list when no emails are persisted")
    void shouldReturnEmptyListWhenNoEmailsArePersisted() {
      // Act
      List<Email> result = emailRepository.findAll();

      // Assert
      assertThat(result).isEmpty();
    }
  }

  @Nested
  @DisplayName("Delete Operations")
  class DeleteOperations {

    @Test
    @DisplayName("should delete email when id exists")
    void shouldDeleteEmailWhenIdExists() {
      // Arrange
      Email savedEmail = emailRepository.saveAndFlush(createEmail());
      Long emailId = savedEmail.getId();

      // Act
      emailRepository.deleteById(emailId);
      emailRepository.flush();

      // Assert
      assertThat(emailRepository.existsById(emailId)).isFalse();
    }

    @Test
    @DisplayName("should decrease count after deleting an email")
    void shouldDecreaseCountAfterDeletingEmail() {
      // Arrange
      Email savedEmail = emailRepository.saveAndFlush(createEmail());
      long countBefore = emailRepository.count();

      // Act
      emailRepository.deleteById(savedEmail.getId());
      emailRepository.flush();

      // Assert
      assertThat(emailRepository.count()).isEqualTo(countBefore - 1);
    }
  }

  private Email createEmail() {
    return createEmail("recipient@example.com", "Email content");
  }

  private Email createEmail(String recipient, String content) {
    return new Email(new EmailRegisterRequest("sender@example.com", recipient, content));
  }
}
