package com.albertsilva.dev.dscatalog.repository;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.Optional;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;

import com.albertsilva.dev.dscatalog.entity.Category;
import com.albertsilva.dev.dscatalog.entity.Product;
import com.albertsilva.dev.dscatalog.factory.CategoryFactory;
import com.albertsilva.dev.dscatalog.factory.ProductFactory;

@DataJpaTest
@DisplayName("ProductRepository Tests")
class ProductRepositoryTest {

  @Autowired
  private TestEntityManager entityManager;

  @Autowired
  private ProductRepository productRepository;

  @Autowired
  private CategoryRepository categoryRepository;

  @Nested
  @DisplayName("Save Operations")
  class SaveOperations {

    @Test
    @DisplayName("should persist product with auto-generated id when id is null")
    void shouldPersistProductWithAutoGeneratedIdWhenIdIsNull() {

      // Arrange
      long countBefore = productRepository.count();

      Product product = ProductFactory.createProduct();
      product.setId(null);

      // Act
      Product savedProduct = productRepository.save(product);

      // Assert
      assertThat(savedProduct.getId()).as("Product id should be auto-generated").isNotNull().isPositive();

      assertThat(productRepository.count()).as("Repository count should increase by one").isEqualTo(countBefore + 1);
    }

    @Test
    @DisplayName("should update product when id exists")
    void shouldUpdateProductWhenIdExists() {

      // Arrange
      Product product = productRepository.saveAndFlush(ProductFactory.createProduct());
      String updatedName = "Updated Name";

      // Act
      product.setName(updatedName);
      Product updatedProduct = productRepository.save(product);

      // Assert
      assertThat(updatedProduct.getName()).as("Product name should be updated").isEqualTo(updatedName);
    }

    @Test
    @DisplayName("should persist product with associated categories")
    void shouldPersistProductWithAssociatedCategories() {

      // Arrange
      Category category = categoryRepository.saveAndFlush(CategoryFactory.createCategory());

      Product product = ProductFactory.createProduct();
      product.getCategories().add(category);

      // Act
      Product savedProduct = productRepository.saveAndFlush(product);

      // Assert
      assertThat(savedProduct.getCategories()).as("Product should contain associated categories").isNotEmpty()
          .contains(category);
    }
  }

  @Nested
  @DisplayName("FindById Operations")
  class FindByIdOperations {

    @Test
    @DisplayName("should return product when id exists")
    void shouldReturnProductWhenIdExists() {

      // Arrange
      Product product = productRepository.saveAndFlush(ProductFactory.createProduct());

      // Act
      Optional<Product> result = productRepository.findById(product.getId());

      // Assert
      assertThat(result).as("Product should be found").isPresent().contains(product);
    }

    @Test
    @DisplayName("should return empty optional when id does not exist")
    void shouldReturnEmptyOptionalWhenIdDoesNotExist() {

      // Arrange
      Long nonExistingId = 999999L;

      // Act
      Optional<Product> result = productRepository.findById(nonExistingId);

      // Assert
      assertThat(result).as("Product should not be found").isEmpty();
    }
  }

  @Nested
  @DisplayName("Delete Operations")
  class DeleteOperations {

    @Test
    @DisplayName("should delete product when id exists")
    void shouldDeleteProductWhenIdExists() {

      // Arrange
      Product product = productRepository.saveAndFlush(ProductFactory.createProduct());
      Long existingId = product.getId();

      // Act
      productRepository.deleteById(existingId);
      productRepository.flush();

      // Assert
      assertThat(productRepository.existsById(existingId)).as("Product should be deleted").isFalse();
    }

    @Test
    @DisplayName("should decrease repository count after delete")
    void shouldDecreaseRepositoryCountAfterDelete() {

      // Arrange
      Product product = productRepository.saveAndFlush(ProductFactory.createProduct());
      long countBefore = productRepository.count();

      // Act
      productRepository.deleteById(product.getId());
      productRepository.flush();

      // Assert
      assertThat(productRepository.count()).as("Repository count should decrease by one").isEqualTo(countBefore - 1);
    }

    @Test
    @DisplayName("should delete product and remove many-to-many associations")
    void shouldDeleteProductAndRemoveManyToManyAssociations() {

      // Arrange
      Category category = categoryRepository.saveAndFlush(CategoryFactory.createCategory());

      Product product = ProductFactory.createProduct();
      product.getCategories().add(category);
      product = productRepository.saveAndFlush(product);

      Long productId = product.getId();

      // Act
      productRepository.deleteById(productId);
      productRepository.flush();

      // Assert
      assertThat(productRepository.existsById(productId)).as("Product should be deleted").isFalse();

      assertThat(countProductCategoryAssociations(productId)).as("Join table associations should be removed").isZero();
    }

    @Test
    @DisplayName("should delete product without deleting associated categories")
    void shouldDeleteProductWithoutDeletingAssociatedCategories() {

      // Arrange
      Category category = categoryRepository.saveAndFlush(CategoryFactory.createCategory());

      Product product = ProductFactory.createProduct();
      product.getCategories().add(category);
      product = productRepository.saveAndFlush(product);

      Long productId = product.getId();
      Long categoryId = category.getId();

      // Act
      productRepository.deleteById(productId);
      productRepository.flush();

      // Assert
      assertThat(productRepository.existsById(productId)).as("Product should be deleted").isFalse();

      assertThat(categoryRepository.existsById(categoryId)).as("Category should remain").isTrue();
    }
  }

  private long countProductCategoryAssociations(Long productId) {
    Number result = (Number) entityManager.getEntityManager()
        .createNativeQuery("SELECT COUNT(*) FROM tb_product_category WHERE product_id = :id")
        .setParameter("id", productId).getSingleResult();

    return result.longValue();
  }
}