package com.albertsilva.dev.dscatalog.repository;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.Optional;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;

import com.albertsilva.dev.dscatalog.domain.user.User;
import com.albertsilva.dev.dscatalog.factory.UserFactory;

@DataJpaTest
@DisplayName("UserRepository Tests")
class UserRepositoryTest {

  @Autowired
  private TestEntityManager entityManager;

  @Autowired
  private UserRepository userRepository;

  @Nested
  @DisplayName("Save Operations")
  class SaveOperations {

    @Test
    @DisplayName("should persist user with auto-generated id when id is null")
    void shouldPersistUserWithAutoGeneratedIdWhenIdIsNull() {

      // Arrange
      long countBefore = userRepository.count();

      User user = UserFactory.createUser();
      user.setId(null);

      // Act
      User savedUser = userRepository.save(user);

      // Assert
      assertThat(savedUser.getId()).as("User id should be auto-generated").isNotNull().isPositive();

      assertThat(userRepository.count()).as("Repository count should increase by one").isEqualTo(countBefore + 1);
    }

    @Test
    @DisplayName("should update user when id exists")
    void shouldUpdateUserWhenIdExists() {

      // Arrange
      User user = userRepository.saveAndFlush(UserFactory.createUser());
      String updatedFirstName = "Updated Name";

      // Act
      user.setFirstName(updatedFirstName);
      User updatedUser = userRepository.save(user);

      // Assert
      assertThat(updatedUser.getFirstName()).as("User first name should be updated").isEqualTo(updatedFirstName);
    }
  }

  @Nested
  @DisplayName("FindById Operations")
  class FindByIdOperations {

    @Test
    @DisplayName("should return user when id exists")
    void shouldReturnUserWhenIdExists() {

      // Arrange
      User user = userRepository.saveAndFlush(UserFactory.createUser());

      // Act
      Optional<User> result = userRepository.findById(user.getId());

      // Assert
      assertThat(result).as("User should be found by id").isPresent();
      assertThat(result.get().getId()).as("User id should match").isEqualTo(user.getId());
    }

    @Test
    @DisplayName("should return empty when id does not exist")
    void shouldReturnEmptyWhenIdDoesNotExist() {

      // Arrange
      // No user with this id

      // Act
      Optional<User> result = userRepository.findById(9999L);

      // Assert
      assertThat(result).as("User should not be found").isEmpty();
    }
  }

  @Nested
  @DisplayName("FindByEmail Operations")
  class FindByEmailOperations {

    @Test
    @DisplayName("should return user when email exists")
    void shouldReturnUserWhenEmailExists() {

      // Arrange
      User user = userRepository.saveAndFlush(UserFactory.createUser());

      // Act
      Optional<User> result = userRepository.findByEmail(user.getEmail());

      // Assert
      assertThat(result).as("User should be found by email").isPresent();
      assertThat(result.get().getEmail()).as("User email should match").isEqualTo(user.getEmail());
    }

    @Test
    @DisplayName("should return empty when email does not exist")
    void shouldReturnEmptyWhenEmailDoesNotExist() {

      // Arrange
      // No user with this email

      // Act
      Optional<User> result = userRepository.findByEmail("nonexistent@gmail.com");

      // Assert
      assertThat(result).as("User should not be found").isEmpty();
    }
  }

  @Nested
  @DisplayName("FindByFirstNameContainingIgnoreCase Operations")
  class FindByFirstNameOperations {

    @Test
    @DisplayName("should return paged users when first name contains search term")
    void shouldReturnPagedUsersWhenFirstNameContains() {

      // Arrange
      User user1 = UserFactory.createUser();
      user1.setFirstName("Eleanor");
      user1.setEmail("eleanor@gmail.com");
      userRepository.saveAndFlush(user1);

      User user2 = UserFactory.createUser();
      user2.setFirstName("Elenice");
      user2.setEmail("elenice@gmail.com");
      userRepository.saveAndFlush(user2);

      Pageable pageable = PageRequest.of(0, 10);

      // Act
      Page<User> result = userRepository.findByFirstNameContainingIgnoreCase("ele", pageable);

      // Assert
      assertThat(result).as("Result should not be empty").isNotEmpty();

      assertThat(result.getTotalElements()).as("Should find 2 users").isEqualTo(2);
    }

    @Test
    @DisplayName("should return empty page when no users match search term")
    void shouldReturnEmptyPageWhenNoUsersMatch() {

      // Arrange
      Pageable pageable = PageRequest.of(0, 10);

      // Act
      Page<User> result = userRepository.findByFirstNameContainingIgnoreCase("xyzabc", pageable);

      // Assert
      assertThat(result).as("Result should be empty").isEmpty();
    }

    @Test
    @DisplayName("should return users ignoring case when searching")
    void shouldReturnUsersIgnoringCase() {

      // Arrange
      User user = userRepository.saveAndFlush(UserFactory.createUser());

      Pageable pageable = PageRequest.of(0, 10);

      // Act
      Page<User> resultLowerCase = userRepository.findByFirstNameContainingIgnoreCase("joão", pageable);
      Page<User> resultUpperCase = userRepository.findByFirstNameContainingIgnoreCase("JOÃO", pageable);

      // Assert
      assertThat(resultLowerCase.getTotalElements()).as("Should find user with lowercase search").isGreaterThan(0);
      assertThat(resultUpperCase.getTotalElements()).as("Should find user with uppercase search").isGreaterThan(0);
    }
  }

  @Nested
  @DisplayName("ExistsByEmailIgnoreCase Operations")
  class ExistsByEmailOperations {

    @Test
    @DisplayName("should return true when email exists ignoring case")
    void shouldReturnTrueWhenEmailExists() {

      // Arrange
      User user = userRepository.saveAndFlush(UserFactory.createUser());

      // Act
      boolean result = userRepository.existsByEmailIgnoreCase(user.getEmail().toUpperCase());

      // Assert
      assertThat(result).as("Email should exist").isTrue();
    }

    @Test
    @DisplayName("should return false when email does not exist")
    void shouldReturnFalseWhenEmailDoesNotExist() {

      // Arrange
      // No user with this email

      // Act
      boolean result = userRepository.existsByEmailIgnoreCase("nonexistent@gmail.com");

      // Assert
      assertThat(result).as("Email should not exist").isFalse();
    }
  }

  @Nested
  @DisplayName("ExistsByEmailIgnoreCaseAndIdNot Operations")
  class ExistsByEmailIgnoreCaseAndIdNotOperations {

    @Test
    @DisplayName("should return false when email belongs to same user")
    void shouldReturnFalseWhenEmailBelongsToSameUser() {

      // Arrange
      User user = userRepository.saveAndFlush(UserFactory.createUser());

      // Act
      boolean result = userRepository.existsByEmailIgnoreCaseAndIdNot(user.getEmail(), user.getId());

      // Assert
      assertThat(result).as("Should return false for same user").isFalse();
    }

    @Test
    @DisplayName("should return true when email belongs to different user")
    void shouldReturnTrueWhenEmailBelongsToDifferentUser() {

      // Arrange
      User user1 = userRepository.saveAndFlush(UserFactory.createUser());

      User user2 = UserFactory.createUser();
      user2.setEmail("another@gmail.com");
      userRepository.saveAndFlush(user2);

      // Act
      boolean result = userRepository.existsByEmailIgnoreCaseAndIdNot(user2.getEmail(), user1.getId());

      // Assert
      assertThat(result).as("Should return true for different user").isTrue();
    }

    @Test
    @DisplayName("should return false when email does not exist")
    void shouldReturnFalseWhenEmailDoesNotExist() {

      // Arrange
      User user = userRepository.saveAndFlush(UserFactory.createUser());

      // Act
      boolean result = userRepository.existsByEmailIgnoreCaseAndIdNot("nonexistent@gmail.com", user.getId());

      // Assert
      assertThat(result).as("Should return false for non-existent email").isFalse();
    }
  }

  @Nested
  @DisplayName("Delete Operations")
  class DeleteOperations {

    @Test
    @DisplayName("should delete user by id")
    void shouldDeleteUserById() {

      // Arrange
      User user = userRepository.saveAndFlush(UserFactory.createUser());
      Long userId = user.getId();

      // Act
      userRepository.deleteById(userId);

      // Assert
      assertThat(userRepository.findById(userId)).as("User should be deleted").isEmpty();
    }
  }

}
