############################################
# Profiles
############################################
spring.profiles.active=${APP_PROFILE:test}

########################################
# Datasource
########################################
spring.jpa.open-in-view=false

##########################################
# Security
##########################################
security.client-id=${CLIENT_ID:myclientid}
security.client-secret=${CLIENT_SECRET:myclientsecret}

##########################################
# JWT Configuration
###########################################
security.jwt.duration=${JWT_DURATION:86400}

##########################################
# CORS Configuration
##########################################
cors.origins=${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}


########################################
# URLs
########################################
backend.url=${BACKEND_URL:http://localhost:8080}
frontend.url=${FRONTEND_URL:http://localhost:5173}

########################################
# JAVAMAIL
########################################
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:test@gmail.com}
spring.mail.password=${MAIL_PASSWORD:123456}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.test-connection=true

##########################################
# Account Activation
##########################################
account.activation.token.hours=${ACTIVATION_TOKEN_HOURS:24}

##########################################
# Account Recovery
##########################################
account.password-recovery.token.minutes=${PASSWORD_RECOVER_TOKEN_MINUTES:30}
