create table tb_category (
    active boolean not null,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    id bigint generated by default as identity,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name varchar(80) not null unique,
    description varchar(255),
    primary key (id)
);