create table tb_product (
    active boolean not null,
    price float(53),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    id bigint generated by default as identity,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    description TEXT,
    img_url varchar(255),
    name varchar(255) not null unique,
    primary key (id)
);
