create table tb_user (
  active boolean not null,
  id bigint generated by default as identity,
  email varchar(255) not null unique,
  first_name varchar(255),
  last_name varchar(255),
  password varchar(255),
  primary key (id)
);