create table tb_token (
  disabled boolean not null,
  created_at TIMESTAMP WITHOUT TIME ZONE not null,
  expire_date TIMESTAMP WITHOUT TIME ZONE not null,
  id bigint generated by default as identity,
  user_id bigint not null,
  token varchar(255) not null unique,
  type varchar(18) not null check (type in ('ACTIVATION', 'PASSWORD_RECOVERY')),
  primary key (id)
);