create table tb_email (
  created_at TIMESTAMP WITHOUT TIME ZONE not null,
  id bigint generated by default as identity,
  content TEXT not null,
  recipient varchar(255) not null,
  sender varchar(255) not null,
  status varchar(10) not null check (status in ('ERROR', 'PENDING', 'SENT')),
  primary key (id)
);
